### ISSUE TITLE
T3 Doors bug out, preventing exiting or entering

### ISSUE THREAD

**Issue by Specops343** [FelixForesight2020/BaseBuildingPlus#15]
Not sure what prompts it, but t3 doors tend to occasionally bug out in a way that prevents entering or exiting through it.  This issue does not seem to happen with gates or any other tier doors. These doors are correctly snapped onto a floor. Sometimes, you can crawl through in a particular way, but this does not seem to always work. The only certain solution is to take down the door and rebuild it. 

Could you please look into fixing this issue? Please see the below for a clip of the bug. 

https://streamable.com/9cetix

**Comment by Chopper666** [comment]
Thanks for the report. This has been a random bug for a while and we haven't been able to find the cause. We are rebuilding the mod currently, so hopefully it won't be a problem in future.

**Comment by baranmod** [comment]
bug still seem to be active. Overall, T3 door seem to be much smaller than T2/T1. Should be bigger by character head.
